### ISSUE TITLE
Curious about Pseudonyms 

### ISSUE THREAD

**Issue by tensor-programming** [watch-devtube/contrib#348]
After browsing the current contributors; I figured that I may like to add a few of my video series to the list. I am confident that my channel would be considered for the platform (16k subs, 1-2 videos a week at least, and been around for almost 3 years now).   My question is whether or not I am allowed to use a Pseudonym as my speaker name.  I have reasons for keeping my real name off of my channel. I do this primarily to avoid potential legal snafus with my day job (contract/freelance developer and consultant).  The pseudonym "Tensor Programming" is not a business name nor is it a collective of people (all videos are made by me alone).  Would this be allowed or is this a problem?  Not asking to use my channel name; just any pseudonym that isn't my full real name would be fine.

**Comment by aadamovich** [comment]
Hi Tensor (should I call you like that :)?)!

No, I don't think it makes sense to define "Tensor Programming" as a speaker since it will be very confusing to the audience. Your channel name is already a good filter by which people should find these videos. If not "Tensor Programming", what kind of pseudonym did you have in mind? Does it have an established Twitter account that you use regularly or some other identity that is visible on the web? But in general, I do not think it will be a good practice to use pseudonyms.

@sizovs what do you think?

btw. I have added your channel to the list. It should be indexed tomorrow.

**Comment by sizovs** [comment]
Hey

I don't think there is an issue with pseudonyms in general. But `Tensor Programming` in particular can confuse people. What about Tensor P. ?

**Comment by tensor-programming** [comment]
Well, I always introduce myself as Tensor in the videos; makes sense to just use that.  When I meant alternative pseudonyms, I mainly meant nicknames and stuff like that. Something that is sort of like my real name but not quite (just to keep things vague legally).  My Twitter account's name is Abeltensor which is yet another Pseudonym that I use for my content.  I guess Tensor P. is fine as well.  Thank you for accommodating my somewhat selfish request.

Since You've added my channel into the platform, Ill just go ahead and filter out the videos that aren't relevant and add the speaker info etc.  I should just make a fork and pr right?

**Comment by sizovs** [comment]
@tensor-programming if you find live stream videos relevant to the audience – let's just leave them. Thanks for your contribution!
